language: scala

env:
  matrix:
    - SELECT_VERSION="++2.10.6 ^^0.13.16-M1"
    - SELECT_VERSION="++2.12.2 ^^1.0.0-RC2"

script:
 - git config --global user.email "example@example.com"
 - git config --global user.name "example"
 - echo '[ui]' > "$HOME/.hgrc"
 - echo 'username = example <example@example.com>' >> "$HOME/.hgrc"
 - sbt "$SELECT_VERSION test"
 - sbt "$SELECT VERSION publishLocal"
 - sbt "$SELECT VERSION scripted"

sudo: false
