language: scala

env:
  matrix:
    - SELECT_VERSION="++2.10.6 ^^0.13.16-M1"
    - SELECT_VERSION="++2.12.2 ^^1.0.0-RC2"

script:
 - git config --global user.email "example@example.com"
 - git config --global user.name "example"
 - echo '[ui]' > "$HOME/.hgrc"
 - echo 'username = example <example@example.com>' >> "$HOME/.hgrc"
 - sbt "$SELECT_VERSION test"
 - sbt "$SELECT VERSION publishLocal"
 - sbt "$SELECT VERSION scripted"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

sudo: false
